sonar.projectKey=devsecops-projectss
sonar.projectName=devsecops-projectss
sonar.organization=devsecops-projectss

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
